[package]
name = "identity"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
argon2.workspace = true
db.workspace = true
serde.workspace = true
sqlx.workspace = true
utoipa.workspace = true
uuid.workspace = true

[lints]
workspace = true
