/* eslint-disable */
import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n\tquery Inventory($propertyId: UUID!, $from: Date!, $to: Date!) {\n\t\tinventory(propertyId: $propertyId, from: $from, to: $to) {\n\t\t\tdate\n\t\t\troomTypeId\n\t\t\tphysical\n\t\t\tsold\n\t\t\toutOfOrder\n\t\t\tavailable\n\t\t}\n\t\tblocks(propertyId: $propertyId, from: $from, to: $to) {\n\t\t\tid\n\t\t\troomId\n\t\t\tfrom\n\t\t\tto\n\t\t\tkind\n\t\t\treasonId\n\t\t\tnote\n\t\t\tversion\n\t\t}\n\t}\n": typeof types.InventoryDocument,
    "\n\tquery Properties {\n\t\tproperties {\n\t\t\tid\n\t\t\tcode\n\t\t\tname\n\t\t\ttimezone\n\t\t\tbaseCurrency\n\t\t\tbusinessDate\n\t\t\tcheckInTime\n\t\t\tcheckOutTime\n\t\t\tversion\n\t\t}\n\t}\n": typeof types.PropertiesDocument,
    "\n\tquery RatePlans($propertyId: UUID!) {\n\t\tratePlans(propertyId: $propertyId) {\n\t\t\tid\n\t\t\tcode\n\t\t\tname\n\t\t\tkind\n\t\t\tsegment\n\t\t\tresidency\n\t\t\tcurrency\n\t\t\tparentId\n\t\t\tdepth\n\t\t\tderiveMode\n\t\t\tderiveValue\n\t\t\troundingStep\n\t\t\textraAdultAmount\n\t\t\tinheritRestrictions\n\t\t\tallowedMealPlans\n\t\t\tcancellationPolicyId\n\t\t\troomTypeIds\n\t\t\tactive\n\t\t\tversion\n\t\t}\n\t\tmealSupplements(propertyId: $propertyId) {\n\t\t\tid\n\t\t\tmealPlan\n\t\t\tcurrency\n\t\t\tadultAmount\n\t\t\tchildAmount\n\t\t\tfrom\n\t\t\tto\n\t\t\tversion\n\t\t}\n\t\tcancellationPolicies(propertyId: $propertyId) {\n\t\t\tid\n\t\t\tname\n\t\t\tversion\n\t\t}\n\t}\n": typeof types.RatePlansDocument,
    "\n\tquery RateGrid($propertyId: UUID!, $ratePlanId: UUID!, $from: Date!, $to: Date!) {\n\t\trateGrid(propertyId: $propertyId, ratePlanId: $ratePlanId, from: $from, to: $to) {\n\t\t\tprices {\n\t\t\t\troomTypeId\n\t\t\t\tdate\n\t\t\t\toccupancy\n\t\t\t\tamount\n\t\t\t}\n\t\t\trestrictions {\n\t\t\t\troomTypeId\n\t\t\t\tdate\n\t\t\t\tclosed\n\t\t\t\tminStay\n\t\t\t\tmaxStay\n\t\t\t\tclosedToArrival\n\t\t\t\tclosedToDeparture\n\t\t\t}\n\t\t}\n\t}\n": typeof types.RateGridDocument,
    "\n\tquery BulkPreview(\n\t\t$propertyId: UUID!\n\t\t$ratePlanId: UUID!\n\t\t$from: Date!\n\t\t$to: Date!\n\t\t$weekdays: [Int!]!\n\t\t$roomTypeIds: [UUID!]!\n\t\t$mode: PriceChangeMode!\n\t\t$value: Int!\n\t) {\n\t\tbulkChangePreview(\n\t\t\tpropertyId: $propertyId\n\t\t\tratePlanId: $ratePlanId\n\t\t\tfrom: $from\n\t\t\tto: $to\n\t\t\tweekdays: $weekdays\n\t\t\troomTypeIds: $roomTypeIds\n\t\t\tmode: $mode\n\t\t\tvalue: $value\n\t\t) {\n\t\t\ttotal\n\t\t\tcells {\n\t\t\t\troomTypeId\n\t\t\t\tdate\n\t\t\t\toccupancy\n\t\t\t\tbefore\n\t\t\t\tafter\n\t\t\t}\n\t\t}\n\t}\n": typeof types.BulkPreviewDocument,
    "\n\tquery Quote(\n\t\t$propertyId: UUID!\n\t\t$roomTypeId: UUID!\n\t\t$ratePlanId: UUID!\n\t\t$mealPlan: MealPlan!\n\t\t$checkIn: Date!\n\t\t$checkOut: Date!\n\t\t$adults: Int!\n\t\t$children: Int!\n\t\t$residency: Residency!\n\t) {\n\t\tquote(\n\t\t\tpropertyId: $propertyId\n\t\t\troomTypeId: $roomTypeId\n\t\t\tratePlanId: $ratePlanId\n\t\t\tmealPlan: $mealPlan\n\t\t\tcheckIn: $checkIn\n\t\t\tcheckOut: $checkOut\n\t\t\tadults: $adults\n\t\t\tchildren: $children\n\t\t\tresidency: $residency\n\t\t) {\n\t\t\tnights {\n\t\t\t\tdate\n\t\t\t\troom\n\t\t\t\tmeal\n\t\t\t}\n\t\t\ttotal\n\t\t\tcurrency\n\t\t\trestrictionsOk\n\t\t\tviolations {\n\t\t\t\tkind\n\t\t\t\tdate\n\t\t\t\tmessage\n\t\t\t}\n\t\t}\n\t}\n": typeof types.QuoteDocument,
    "\n\tquery Availability(\n\t\t$propertyId: UUID!\n\t\t$checkIn: Date!\n\t\t$checkOut: Date!\n\t\t$adults: Int!\n\t\t$children: Int!\n\t\t$residency: Residency!\n\t) {\n\t\tavailability(\n\t\t\tpropertyId: $propertyId\n\t\t\tcheckIn: $checkIn\n\t\t\tcheckOut: $checkOut\n\t\t\tadults: $adults\n\t\t\tchildren: $children\n\t\t\tresidency: $residency\n\t\t) {\n\t\t\troomTypeId\n\t\t\tcode\n\t\t\tname\n\t\t\tfree\n\t\t\toffers {\n\t\t\t\tratePlanId\n\t\t\t\tratePlanCode\n\t\t\t\tmealPlan\n\t\t\t\ttotal\n\t\t\t\tcurrency\n\t\t\t\trestrictionsOk\n\t\t\t\tviolations {\n\t\t\t\t\tkind\n\t\t\t\t\tmessage\n\t\t\t\t}\n\t\t\t\tnights {\n\t\t\t\t\tdate\n\t\t\t\t\troom\n\t\t\t\t\tmeal\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": typeof types.AvailabilityDocument,
    "\n\tquery ReservationList(\n\t\t$p: UUID!\n\t\t$filter: ReservationFilter\n\t\t$sort: ReservationSort\n\t\t$first: Int\n\t\t$after: String\n\t\t$withCount: Boolean!\n\t) {\n\t\treservations(propertyId: $p, filter: $filter, sort: $sort, first: $first, after: $after) {\n\t\t\tnodes {\n\t\t\t\tid\n\t\t\t\treservationId\n\t\t\t\tconfirmationNo\n\t\t\t\tguestName\n\t\t\t\tarrival\n\t\t\t\tdeparture\n\t\t\t\tnights\n\t\t\t\troomTypeCode\n\t\t\t\troomNumber\n\t\t\t\tstatus\n\t\t\t\tsource\n\t\t\t\ttotal\n\t\t\t\tcurrency\n\t\t\t\tversion\n\t\t\t}\n\t\t\tpageInfo {\n\t\t\t\tendCursor\n\t\t\t\thasNextPage\n\t\t\t}\n\t\t\ttotalCount @include(if: $withCount)\n\t\t}\n\t}\n": typeof types.ReservationListDocument,
    "\n\tquery Reservation($p: UUID!, $id: UUID!) {\n\t\treservation(propertyId: $p, id: $id) {\n\t\t\tid\n\t\t\tconfirmationNo\n\t\t\tstatus\n\t\t\tsource\n\t\t\tnotes\n\t\t\tcreatedAt\n\t\t\tversion\n\t\t\tbooker {\n\t\t\t\tid\n\t\t\t\tfirstName\n\t\t\t\tlastName\n\t\t\t\temail\n\t\t\t\tphone\n\t\t\t\tcountry\n\t\t\t\tresidency\n\t\t\t\tidDocType\n\t\t\t\tidDocMasked\n\t\t\t\tnotes\n\t\t\t\tversion\n\t\t\t}\n\t\t\ttotals {\n\t\t\t\tcurrency\n\t\t\t\tamount\n\t\t\t}\n\t\t\trooms {\n\t\t\t\tid\n\t\t\t\tversion\n\t\t\t\tstatus\n\t\t\t\tcheckIn\n\t\t\t\tcheckOut\n\t\t\t\tadults\n\t\t\t\tchildren\n\t\t\t\tmealPlan\n\t\t\t\ttotal\n\t\t\t\tcurrency\n\t\t\t\troomType {\n\t\t\t\t\tid\n\t\t\t\t\tcode\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t\troom {\n\t\t\t\t\tid\n\t\t\t\t\tnumber\n\t\t\t\t}\n\t\t\t\tratePlan {\n\t\t\t\t\tid\n\t\t\t\t\tcode\n\t\t\t\t}\n\t\t\t\tprimaryGuest {\n\t\t\t\t\tid\n\t\t\t\t\tfirstName\n\t\t\t\t\tlastName\n\t\t\t\t\tresidency\n\t\t\t\t\tidDocType\n\t\t\t\t\tidDocMasked\n\t\t\t\t}\n\t\t\t\tnights {\n\t\t\t\t\tdate\n\t\t\t\t\troom\n\t\t\t\t\tmeal\n\t\t\t\t}\n\t\t\t\tcancellationTerms {\n\t\t\t\t\trules {\n\t\t\t\t\t\tdaysBeforeArrival\n\t\t\t\t\t\tpenalty {\n\t\t\t\t\t\t\tkind\n\t\t\t\t\t\t\tvalue\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\tnoShow {\n\t\t\t\t\t\tkind\n\t\t\t\t\t\tvalue\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t\tcancellationPenalty\n\t\t\t\tcancelledAt\n\t\t\t\trecordedPenalty\n\t\t\t}\n\t\t\thistory {\n\t\t\t\taction\n\t\t\t\tat\n\t\t\t\tactorName\n\t\t\t\tdata\n\t\t\t}\n\t\t}\n\t}\n": typeof types.ReservationDocument,
    "\n\tquery Guests($propertyId: UUID!, $search: String, $first: Int) {\n\t\tguests(propertyId: $propertyId, search: $search, first: $first) {\n\t\t\tid\n\t\t\tfirstName\n\t\t\tlastName\n\t\t\temail\n\t\t\tphone\n\t\t\tcountry\n\t\t\tresidency\n\t\t\tidDocType\n\t\t\tidDocMasked\n\t\t\tnotes\n\t\t\tversion\n\t\t}\n\t}\n": typeof types.GuestsDocument,
    "\n\tquery FreeRooms($propertyId: UUID!, $roomTypeId: UUID!, $checkIn: Date!, $checkOut: Date!) {\n\t\tfreeRooms(\n\t\t\tpropertyId: $propertyId\n\t\t\troomTypeId: $roomTypeId\n\t\t\tcheckIn: $checkIn\n\t\t\tcheckOut: $checkOut\n\t\t) {\n\t\t\tid\n\t\t\tnumber\n\t\t\tsection\n\t\t}\n\t}\n": typeof types.FreeRoomsDocument,
    "\n\tquery RoomTypes($propertyId: UUID!) {\n\t\troomTypes(propertyId: $propertyId) {\n\t\t\tid\n\t\t\tcode\n\t\t\tname\n\t\t\tbaseOccupancy\n\t\t\tmaxAdults\n\t\t\tmaxChildren\n\t\t\tmaxOccupancy\n\t\t\tamenities\n\t\t\tsortOrder\n\t\t\tactive\n\t\t\tversion\n\t\t}\n\t}\n": typeof types.RoomTypesDocument,
    "\n\tquery Rooms($propertyId: UUID!) {\n\t\trooms(propertyId: $propertyId) {\n\t\t\tid\n\t\t\troomTypeId\n\t\t\tnumber\n\t\t\tfloor\n\t\t\tsectionId\n\t\t\tactive\n\t\t\tsortOrder\n\t\t\tversion\n\t\t}\n\t\tsections(propertyId: $propertyId) {\n\t\t\tid\n\t\t\tname\n\t\t\tversion\n\t\t}\n\t\tblockReasons(propertyId: $propertyId) {\n\t\t\tid\n\t\t\tcode\n\t\t\tlabel\n\t\t\tdefaultKind\n\t\t\tactive\n\t\t}\n\t}\n": typeof types.RoomsDocument,
};
const documents: Documents = {
    "\n\tquery Inventory($propertyId: UUID!, $from: Date!, $to: Date!) {\n\t\tinventory(propertyId: $propertyId, from: $from, to: $to) {\n\t\t\tdate\n\t\t\troomTypeId\n\t\t\tphysical\n\t\t\tsold\n\t\t\toutOfOrder\n\t\t\tavailable\n\t\t}\n\t\tblocks(propertyId: $propertyId, from: $from, to: $to) {\n\t\t\tid\n\t\t\troomId\n\t\t\tfrom\n\t\t\tto\n\t\t\tkind\n\t\t\treasonId\n\t\t\tnote\n\t\t\tversion\n\t\t}\n\t}\n": types.InventoryDocument,
    "\n\tquery Properties {\n\t\tproperties {\n\t\t\tid\n\t\t\tcode\n\t\t\tname\n\t\t\ttimezone\n\t\t\tbaseCurrency\n\t\t\tbusinessDate\n\t\t\tcheckInTime\n\t\t\tcheckOutTime\n\t\t\tversion\n\t\t}\n\t}\n": types.PropertiesDocument,
    "\n\tquery RatePlans($propertyId: UUID!) {\n\t\tratePlans(propertyId: $propertyId) {\n\t\t\tid\n\t\t\tcode\n\t\t\tname\n\t\t\tkind\n\t\t\tsegment\n\t\t\tresidency\n\t\t\tcurrency\n\t\t\tparentId\n\t\t\tdepth\n\t\t\tderiveMode\n\t\t\tderiveValue\n\t\t\troundingStep\n\t\t\textraAdultAmount\n\t\t\tinheritRestrictions\n\t\t\tallowedMealPlans\n\t\t\tcancellationPolicyId\n\t\t\troomTypeIds\n\t\t\tactive\n\t\t\tversion\n\t\t}\n\t\tmealSupplements(propertyId: $propertyId) {\n\t\t\tid\n\t\t\tmealPlan\n\t\t\tcurrency\n\t\t\tadultAmount\n\t\t\tchildAmount\n\t\t\tfrom\n\t\t\tto\n\t\t\tversion\n\t\t}\n\t\tcancellationPolicies(propertyId: $propertyId) {\n\t\t\tid\n\t\t\tname\n\t\t\tversion\n\t\t}\n\t}\n": types.RatePlansDocument,
    "\n\tquery RateGrid($propertyId: UUID!, $ratePlanId: UUID!, $from: Date!, $to: Date!) {\n\t\trateGrid(propertyId: $propertyId, ratePlanId: $ratePlanId, from: $from, to: $to) {\n\t\t\tprices {\n\t\t\t\troomTypeId\n\t\t\t\tdate\n\t\t\t\toccupancy\n\t\t\t\tamount\n\t\t\t}\n\t\t\trestrictions {\n\t\t\t\troomTypeId\n\t\t\t\tdate\n\t\t\t\tclosed\n\t\t\t\tminStay\n\t\t\t\tmaxStay\n\t\t\t\tclosedToArrival\n\t\t\t\tclosedToDeparture\n\t\t\t}\n\t\t}\n\t}\n": types.RateGridDocument,
    "\n\tquery BulkPreview(\n\t\t$propertyId: UUID!\n\t\t$ratePlanId: UUID!\n\t\t$from: Date!\n\t\t$to: Date!\n\t\t$weekdays: [Int!]!\n\t\t$roomTypeIds: [UUID!]!\n\t\t$mode: PriceChangeMode!\n\t\t$value: Int!\n\t) {\n\t\tbulkChangePreview(\n\t\t\tpropertyId: $propertyId\n\t\t\tratePlanId: $ratePlanId\n\t\t\tfrom: $from\n\t\t\tto: $to\n\t\t\tweekdays: $weekdays\n\t\t\troomTypeIds: $roomTypeIds\n\t\t\tmode: $mode\n\t\t\tvalue: $value\n\t\t) {\n\t\t\ttotal\n\t\t\tcells {\n\t\t\t\troomTypeId\n\t\t\t\tdate\n\t\t\t\toccupancy\n\t\t\t\tbefore\n\t\t\t\tafter\n\t\t\t}\n\t\t}\n\t}\n": types.BulkPreviewDocument,
    "\n\tquery Quote(\n\t\t$propertyId: UUID!\n\t\t$roomTypeId: UUID!\n\t\t$ratePlanId: UUID!\n\t\t$mealPlan: MealPlan!\n\t\t$checkIn: Date!\n\t\t$checkOut: Date!\n\t\t$adults: Int!\n\t\t$children: Int!\n\t\t$residency: Residency!\n\t) {\n\t\tquote(\n\t\t\tpropertyId: $propertyId\n\t\t\troomTypeId: $roomTypeId\n\t\t\tratePlanId: $ratePlanId\n\t\t\tmealPlan: $mealPlan\n\t\t\tcheckIn: $checkIn\n\t\t\tcheckOut: $checkOut\n\t\t\tadults: $adults\n\t\t\tchildren: $children\n\t\t\tresidency: $residency\n\t\t) {\n\t\t\tnights {\n\t\t\t\tdate\n\t\t\t\troom\n\t\t\t\tmeal\n\t\t\t}\n\t\t\ttotal\n\t\t\tcurrency\n\t\t\trestrictionsOk\n\t\t\tviolations {\n\t\t\t\tkind\n\t\t\t\tdate\n\t\t\t\tmessage\n\t\t\t}\n\t\t}\n\t}\n": types.QuoteDocument,
    "\n\tquery Availability(\n\t\t$propertyId: UUID!\n\t\t$checkIn: Date!\n\t\t$checkOut: Date!\n\t\t$adults: Int!\n\t\t$children: Int!\n\t\t$residency: Residency!\n\t) {\n\t\tavailability(\n\t\t\tpropertyId: $propertyId\n\t\t\tcheckIn: $checkIn\n\t\t\tcheckOut: $checkOut\n\t\t\tadults: $adults\n\t\t\tchildren: $children\n\t\t\tresidency: $residency\n\t\t) {\n\t\t\troomTypeId\n\t\t\tcode\n\t\t\tname\n\t\t\tfree\n\t\t\toffers {\n\t\t\t\tratePlanId\n\t\t\t\tratePlanCode\n\t\t\t\tmealPlan\n\t\t\t\ttotal\n\t\t\t\tcurrency\n\t\t\t\trestrictionsOk\n\t\t\t\tviolations {\n\t\t\t\t\tkind\n\t\t\t\t\tmessage\n\t\t\t\t}\n\t\t\t\tnights {\n\t\t\t\t\tdate\n\t\t\t\t\troom\n\t\t\t\t\tmeal\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.AvailabilityDocument,
    "\n\tquery ReservationList(\n\t\t$p: UUID!\n\t\t$filter: ReservationFilter\n\t\t$sort: ReservationSort\n\t\t$first: Int\n\t\t$after: String\n\t\t$withCount: Boolean!\n\t) {\n\t\treservations(propertyId: $p, filter: $filter, sort: $sort, first: $first, after: $after) {\n\t\t\tnodes {\n\t\t\t\tid\n\t\t\t\treservationId\n\t\t\t\tconfirmationNo\n\t\t\t\tguestName\n\t\t\t\tarrival\n\t\t\t\tdeparture\n\t\t\t\tnights\n\t\t\t\troomTypeCode\n\t\t\t\troomNumber\n\t\t\t\tstatus\n\t\t\t\tsource\n\t\t\t\ttotal\n\t\t\t\tcurrency\n\t\t\t\tversion\n\t\t\t}\n\t\t\tpageInfo {\n\t\t\t\tendCursor\n\t\t\t\thasNextPage\n\t\t\t}\n\t\t\ttotalCount @include(if: $withCount)\n\t\t}\n\t}\n": types.ReservationListDocument,
    "\n\tquery Reservation($p: UUID!, $id: UUID!) {\n\t\treservation(propertyId: $p, id: $id) {\n\t\t\tid\n\t\t\tconfirmationNo\n\t\t\tstatus\n\t\t\tsource\n\t\t\tnotes\n\t\t\tcreatedAt\n\t\t\tversion\n\t\t\tbooker {\n\t\t\t\tid\n\t\t\t\tfirstName\n\t\t\t\tlastName\n\t\t\t\temail\n\t\t\t\tphone\n\t\t\t\tcountry\n\t\t\t\tresidency\n\t\t\t\tidDocType\n\t\t\t\tidDocMasked\n\t\t\t\tnotes\n\t\t\t\tversion\n\t\t\t}\n\t\t\ttotals {\n\t\t\t\tcurrency\n\t\t\t\tamount\n\t\t\t}\n\t\t\trooms {\n\t\t\t\tid\n\t\t\t\tversion\n\t\t\t\tstatus\n\t\t\t\tcheckIn\n\t\t\t\tcheckOut\n\t\t\t\tadults\n\t\t\t\tchildren\n\t\t\t\tmealPlan\n\t\t\t\ttotal\n\t\t\t\tcurrency\n\t\t\t\troomType {\n\t\t\t\t\tid\n\t\t\t\t\tcode\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t\troom {\n\t\t\t\t\tid\n\t\t\t\t\tnumber\n\t\t\t\t}\n\t\t\t\tratePlan {\n\t\t\t\t\tid\n\t\t\t\t\tcode\n\t\t\t\t}\n\t\t\t\tprimaryGuest {\n\t\t\t\t\tid\n\t\t\t\t\tfirstName\n\t\t\t\t\tlastName\n\t\t\t\t\tresidency\n\t\t\t\t\tidDocType\n\t\t\t\t\tidDocMasked\n\t\t\t\t}\n\t\t\t\tnights {\n\t\t\t\t\tdate\n\t\t\t\t\troom\n\t\t\t\t\tmeal\n\t\t\t\t}\n\t\t\t\tcancellationTerms {\n\t\t\t\t\trules {\n\t\t\t\t\t\tdaysBeforeArrival\n\t\t\t\t\t\tpenalty {\n\t\t\t\t\t\t\tkind\n\t\t\t\t\t\t\tvalue\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\tnoShow {\n\t\t\t\t\t\tkind\n\t\t\t\t\t\tvalue\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t\tcancellationPenalty\n\t\t\t\tcancelledAt\n\t\t\t\trecordedPenalty\n\t\t\t}\n\t\t\thistory {\n\t\t\t\taction\n\t\t\t\tat\n\t\t\t\tactorName\n\t\t\t\tdata\n\t\t\t}\n\t\t}\n\t}\n": types.ReservationDocument,
    "\n\tquery Guests($propertyId: UUID!, $search: String, $first: Int) {\n\t\tguests(propertyId: $propertyId, search: $search, first: $first) {\n\t\t\tid\n\t\t\tfirstName\n\t\t\tlastName\n\t\t\temail\n\t\t\tphone\n\t\t\tcountry\n\t\t\tresidency\n\t\t\tidDocType\n\t\t\tidDocMasked\n\t\t\tnotes\n\t\t\tversion\n\t\t}\n\t}\n": types.GuestsDocument,
    "\n\tquery FreeRooms($propertyId: UUID!, $roomTypeId: UUID!, $checkIn: Date!, $checkOut: Date!) {\n\t\tfreeRooms(\n\t\t\tpropertyId: $propertyId\n\t\t\troomTypeId: $roomTypeId\n\t\t\tcheckIn: $checkIn\n\t\t\tcheckOut: $checkOut\n\t\t) {\n\t\t\tid\n\t\t\tnumber\n\t\t\tsection\n\t\t}\n\t}\n": types.FreeRoomsDocument,
    "\n\tquery RoomTypes($propertyId: UUID!) {\n\t\troomTypes(propertyId: $propertyId) {\n\t\t\tid\n\t\t\tcode\n\t\t\tname\n\t\t\tbaseOccupancy\n\t\t\tmaxAdults\n\t\t\tmaxChildren\n\t\t\tmaxOccupancy\n\t\t\tamenities\n\t\t\tsortOrder\n\t\t\tactive\n\t\t\tversion\n\t\t}\n\t}\n": types.RoomTypesDocument,
    "\n\tquery Rooms($propertyId: UUID!) {\n\t\trooms(propertyId: $propertyId) {\n\t\t\tid\n\t\t\troomTypeId\n\t\t\tnumber\n\t\t\tfloor\n\t\t\tsectionId\n\t\t\tactive\n\t\t\tsortOrder\n\t\t\tversion\n\t\t}\n\t\tsections(propertyId: $propertyId) {\n\t\t\tid\n\t\t\tname\n\t\t\tversion\n\t\t}\n\t\tblockReasons(propertyId: $propertyId) {\n\t\t\tid\n\t\t\tcode\n\t\t\tlabel\n\t\t\tdefaultKind\n\t\t\tactive\n\t\t}\n\t}\n": types.RoomsDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery Inventory($propertyId: UUID!, $from: Date!, $to: Date!) {\n\t\tinventory(propertyId: $propertyId, from: $from, to: $to) {\n\t\t\tdate\n\t\t\troomTypeId\n\t\t\tphysical\n\t\t\tsold\n\t\t\toutOfOrder\n\t\t\tavailable\n\t\t}\n\t\tblocks(propertyId: $propertyId, from: $from, to: $to) {\n\t\t\tid\n\t\t\troomId\n\t\t\tfrom\n\t\t\tto\n\t\t\tkind\n\t\t\treasonId\n\t\t\tnote\n\t\t\tversion\n\t\t}\n\t}\n"): typeof import('./graphql').InventoryDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery Properties {\n\t\tproperties {\n\t\t\tid\n\t\t\tcode\n\t\t\tname\n\t\t\ttimezone\n\t\t\tbaseCurrency\n\t\t\tbusinessDate\n\t\t\tcheckInTime\n\t\t\tcheckOutTime\n\t\t\tversion\n\t\t}\n\t}\n"): typeof import('./graphql').PropertiesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery RatePlans($propertyId: UUID!) {\n\t\tratePlans(propertyId: $propertyId) {\n\t\t\tid\n\t\t\tcode\n\t\t\tname\n\t\t\tkind\n\t\t\tsegment\n\t\t\tresidency\n\t\t\tcurrency\n\t\t\tparentId\n\t\t\tdepth\n\t\t\tderiveMode\n\t\t\tderiveValue\n\t\t\troundingStep\n\t\t\textraAdultAmount\n\t\t\tinheritRestrictions\n\t\t\tallowedMealPlans\n\t\t\tcancellationPolicyId\n\t\t\troomTypeIds\n\t\t\tactive\n\t\t\tversion\n\t\t}\n\t\tmealSupplements(propertyId: $propertyId) {\n\t\t\tid\n\t\t\tmealPlan\n\t\t\tcurrency\n\t\t\tadultAmount\n\t\t\tchildAmount\n\t\t\tfrom\n\t\t\tto\n\t\t\tversion\n\t\t}\n\t\tcancellationPolicies(propertyId: $propertyId) {\n\t\t\tid\n\t\t\tname\n\t\t\tversion\n\t\t}\n\t}\n"): typeof import('./graphql').RatePlansDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery RateGrid($propertyId: UUID!, $ratePlanId: UUID!, $from: Date!, $to: Date!) {\n\t\trateGrid(propertyId: $propertyId, ratePlanId: $ratePlanId, from: $from, to: $to) {\n\t\t\tprices {\n\t\t\t\troomTypeId\n\t\t\t\tdate\n\t\t\t\toccupancy\n\t\t\t\tamount\n\t\t\t}\n\t\t\trestrictions {\n\t\t\t\troomTypeId\n\t\t\t\tdate\n\t\t\t\tclosed\n\t\t\t\tminStay\n\t\t\t\tmaxStay\n\t\t\t\tclosedToArrival\n\t\t\t\tclosedToDeparture\n\t\t\t}\n\t\t}\n\t}\n"): typeof import('./graphql').RateGridDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery BulkPreview(\n\t\t$propertyId: UUID!\n\t\t$ratePlanId: UUID!\n\t\t$from: Date!\n\t\t$to: Date!\n\t\t$weekdays: [Int!]!\n\t\t$roomTypeIds: [UUID!]!\n\t\t$mode: PriceChangeMode!\n\t\t$value: Int!\n\t) {\n\t\tbulkChangePreview(\n\t\t\tpropertyId: $propertyId\n\t\t\tratePlanId: $ratePlanId\n\t\t\tfrom: $from\n\t\t\tto: $to\n\t\t\tweekdays: $weekdays\n\t\t\troomTypeIds: $roomTypeIds\n\t\t\tmode: $mode\n\t\t\tvalue: $value\n\t\t) {\n\t\t\ttotal\n\t\t\tcells {\n\t\t\t\troomTypeId\n\t\t\t\tdate\n\t\t\t\toccupancy\n\t\t\t\tbefore\n\t\t\t\tafter\n\t\t\t}\n\t\t}\n\t}\n"): typeof import('./graphql').BulkPreviewDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery Quote(\n\t\t$propertyId: UUID!\n\t\t$roomTypeId: UUID!\n\t\t$ratePlanId: UUID!\n\t\t$mealPlan: MealPlan!\n\t\t$checkIn: Date!\n\t\t$checkOut: Date!\n\t\t$adults: Int!\n\t\t$children: Int!\n\t\t$residency: Residency!\n\t) {\n\t\tquote(\n\t\t\tpropertyId: $propertyId\n\t\t\troomTypeId: $roomTypeId\n\t\t\tratePlanId: $ratePlanId\n\t\t\tmealPlan: $mealPlan\n\t\t\tcheckIn: $checkIn\n\t\t\tcheckOut: $checkOut\n\t\t\tadults: $adults\n\t\t\tchildren: $children\n\t\t\tresidency: $residency\n\t\t) {\n\t\t\tnights {\n\t\t\t\tdate\n\t\t\t\troom\n\t\t\t\tmeal\n\t\t\t}\n\t\t\ttotal\n\t\t\tcurrency\n\t\t\trestrictionsOk\n\t\t\tviolations {\n\t\t\t\tkind\n\t\t\t\tdate\n\t\t\t\tmessage\n\t\t\t}\n\t\t}\n\t}\n"): typeof import('./graphql').QuoteDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery Availability(\n\t\t$propertyId: UUID!\n\t\t$checkIn: Date!\n\t\t$checkOut: Date!\n\t\t$adults: Int!\n\t\t$children: Int!\n\t\t$residency: Residency!\n\t) {\n\t\tavailability(\n\t\t\tpropertyId: $propertyId\n\t\t\tcheckIn: $checkIn\n\t\t\tcheckOut: $checkOut\n\t\t\tadults: $adults\n\t\t\tchildren: $children\n\t\t\tresidency: $residency\n\t\t) {\n\t\t\troomTypeId\n\t\t\tcode\n\t\t\tname\n\t\t\tfree\n\t\t\toffers {\n\t\t\t\tratePlanId\n\t\t\t\tratePlanCode\n\t\t\t\tmealPlan\n\t\t\t\ttotal\n\t\t\t\tcurrency\n\t\t\t\trestrictionsOk\n\t\t\t\tviolations {\n\t\t\t\t\tkind\n\t\t\t\t\tmessage\n\t\t\t\t}\n\t\t\t\tnights {\n\t\t\t\t\tdate\n\t\t\t\t\troom\n\t\t\t\t\tmeal\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): typeof import('./graphql').AvailabilityDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery ReservationList(\n\t\t$p: UUID!\n\t\t$filter: ReservationFilter\n\t\t$sort: ReservationSort\n\t\t$first: Int\n\t\t$after: String\n\t\t$withCount: Boolean!\n\t) {\n\t\treservations(propertyId: $p, filter: $filter, sort: $sort, first: $first, after: $after) {\n\t\t\tnodes {\n\t\t\t\tid\n\t\t\t\treservationId\n\t\t\t\tconfirmationNo\n\t\t\t\tguestName\n\t\t\t\tarrival\n\t\t\t\tdeparture\n\t\t\t\tnights\n\t\t\t\troomTypeCode\n\t\t\t\troomNumber\n\t\t\t\tstatus\n\t\t\t\tsource\n\t\t\t\ttotal\n\t\t\t\tcurrency\n\t\t\t\tversion\n\t\t\t}\n\t\t\tpageInfo {\n\t\t\t\tendCursor\n\t\t\t\thasNextPage\n\t\t\t}\n\t\t\ttotalCount @include(if: $withCount)\n\t\t}\n\t}\n"): typeof import('./graphql').ReservationListDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery Reservation($p: UUID!, $id: UUID!) {\n\t\treservation(propertyId: $p, id: $id) {\n\t\t\tid\n\t\t\tconfirmationNo\n\t\t\tstatus\n\t\t\tsource\n\t\t\tnotes\n\t\t\tcreatedAt\n\t\t\tversion\n\t\t\tbooker {\n\t\t\t\tid\n\t\t\t\tfirstName\n\t\t\t\tlastName\n\t\t\t\temail\n\t\t\t\tphone\n\t\t\t\tcountry\n\t\t\t\tresidency\n\t\t\t\tidDocType\n\t\t\t\tidDocMasked\n\t\t\t\tnotes\n\t\t\t\tversion\n\t\t\t}\n\t\t\ttotals {\n\t\t\t\tcurrency\n\t\t\t\tamount\n\t\t\t}\n\t\t\trooms {\n\t\t\t\tid\n\t\t\t\tversion\n\t\t\t\tstatus\n\t\t\t\tcheckIn\n\t\t\t\tcheckOut\n\t\t\t\tadults\n\t\t\t\tchildren\n\t\t\t\tmealPlan\n\t\t\t\ttotal\n\t\t\t\tcurrency\n\t\t\t\troomType {\n\t\t\t\t\tid\n\t\t\t\t\tcode\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t\troom {\n\t\t\t\t\tid\n\t\t\t\t\tnumber\n\t\t\t\t}\n\t\t\t\tratePlan {\n\t\t\t\t\tid\n\t\t\t\t\tcode\n\t\t\t\t}\n\t\t\t\tprimaryGuest {\n\t\t\t\t\tid\n\t\t\t\t\tfirstName\n\t\t\t\t\tlastName\n\t\t\t\t\tresidency\n\t\t\t\t\tidDocType\n\t\t\t\t\tidDocMasked\n\t\t\t\t}\n\t\t\t\tnights {\n\t\t\t\t\tdate\n\t\t\t\t\troom\n\t\t\t\t\tmeal\n\t\t\t\t}\n\t\t\t\tcancellationTerms {\n\t\t\t\t\trules {\n\t\t\t\t\t\tdaysBeforeArrival\n\t\t\t\t\t\tpenalty {\n\t\t\t\t\t\t\tkind\n\t\t\t\t\t\t\tvalue\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\tnoShow {\n\t\t\t\t\t\tkind\n\t\t\t\t\t\tvalue\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t\tcancellationPenalty\n\t\t\t\tcancelledAt\n\t\t\t\trecordedPenalty\n\t\t\t}\n\t\t\thistory {\n\t\t\t\taction\n\t\t\t\tat\n\t\t\t\tactorName\n\t\t\t\tdata\n\t\t\t}\n\t\t}\n\t}\n"): typeof import('./graphql').ReservationDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery Guests($propertyId: UUID!, $search: String, $first: Int) {\n\t\tguests(propertyId: $propertyId, search: $search, first: $first) {\n\t\t\tid\n\t\t\tfirstName\n\t\t\tlastName\n\t\t\temail\n\t\t\tphone\n\t\t\tcountry\n\t\t\tresidency\n\t\t\tidDocType\n\t\t\tidDocMasked\n\t\t\tnotes\n\t\t\tversion\n\t\t}\n\t}\n"): typeof import('./graphql').GuestsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery FreeRooms($propertyId: UUID!, $roomTypeId: UUID!, $checkIn: Date!, $checkOut: Date!) {\n\t\tfreeRooms(\n\t\t\tpropertyId: $propertyId\n\t\t\troomTypeId: $roomTypeId\n\t\t\tcheckIn: $checkIn\n\t\t\tcheckOut: $checkOut\n\t\t) {\n\t\t\tid\n\t\t\tnumber\n\t\t\tsection\n\t\t}\n\t}\n"): typeof import('./graphql').FreeRoomsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery RoomTypes($propertyId: UUID!) {\n\t\troomTypes(propertyId: $propertyId) {\n\t\t\tid\n\t\t\tcode\n\t\t\tname\n\t\t\tbaseOccupancy\n\t\t\tmaxAdults\n\t\t\tmaxChildren\n\t\t\tmaxOccupancy\n\t\t\tamenities\n\t\t\tsortOrder\n\t\t\tactive\n\t\t\tversion\n\t\t}\n\t}\n"): typeof import('./graphql').RoomTypesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery Rooms($propertyId: UUID!) {\n\t\trooms(propertyId: $propertyId) {\n\t\t\tid\n\t\t\troomTypeId\n\t\t\tnumber\n\t\t\tfloor\n\t\t\tsectionId\n\t\t\tactive\n\t\t\tsortOrder\n\t\t\tversion\n\t\t}\n\t\tsections(propertyId: $propertyId) {\n\t\t\tid\n\t\t\tname\n\t\t\tversion\n\t\t}\n\t\tblockReasons(propertyId: $propertyId) {\n\t\t\tid\n\t\t\tcode\n\t\t\tlabel\n\t\t\tdefaultKind\n\t\t\tactive\n\t\t}\n\t}\n"): typeof import('./graphql').RoomsDocument;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
