[package]
name = "db"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
sqlx.workspace = true
uuid.workspace = true

[features]
testing = []

[dev-dependencies]
db = { workspace = true, features = ["testing"] }
tokio.workspace = true

[lints]
workspace = true
