//! The allowlist of GraphQL documents the web app was built with, generated by GraphQL Codegen.
//! Production runs only these, by id; everything else is a 400.

use async_graphql::parser::parse_query;
use async_graphql::parser::types::ExecutableDocument;
use sha2::{Digest, Sha256};
use std::collections::HashMap;
use std::fmt::Write;
use std::sync::LazyLock;

/// A persisted document: its text, and the text parsed once, so a request by id does not parse it again.
pub struct Document {
    pub text: String,
    pub parsed: ExecutableDocument,
}

/// Document id (`sha256:<hex>`) to document.
static DOCUMENTS: LazyLock<HashMap<String, Document>> = LazyLock::new(|| {
    let texts: HashMap<String, String> =
        serde_json::from_str(include_str!("../../../web/pms/src/lib/api/gql/persisted-documents.json"))
            .expect("persisted-documents.json is a map of document ids to query text");
    texts
        .into_iter()
        .map(|(id, text)| {
            let parsed = parse_query(&text).expect("persisted-documents.json holds only valid queries");
            (id, Document { text, parsed })
        })
        .collect()
});

pub fn documents() -> &'static HashMap<String, Document> {
    &DOCUMENTS
}

/// Parses every document now, so a bad generated file stops the server at startup, not on a request.
pub fn load() {
    LazyLock::force(&DOCUMENTS);
}

/// The id Codegen gives `text`.
pub fn document_id(text: &str) -> String {
    let digest = Sha256::digest(text.as_bytes());
    digest.iter().fold(String::from("sha256:"), |mut id, byte| {
        // Writing to a `String` cannot fail.
        let _ = write!(id, "{byte:02x}");
        id
    })
}
