//! The allowlist of GraphQL documents the web app was built with, generated by GraphQL Codegen.
//! Production runs only these, by id; everything else is a 400.

use sha2::{Digest, Sha256};
use std::collections::HashMap;
use std::fmt::Write;
use std::sync::LazyLock;

/// Document id (`sha256:<hex>`) to query text.
static DOCUMENTS: LazyLock<HashMap<String, String>> = LazyLock::new(|| {
    serde_json::from_str(include_str!("../../../web/pms/src/lib/api/gql/persisted-documents.json"))
        .expect("persisted-documents.json is a map of document ids to query text")
});

pub fn documents() -> &'static HashMap<String, String> {
    &DOCUMENTS
}

/// The id Codegen gives `text`.
pub fn document_id(text: &str) -> String {
    let digest = Sha256::digest(text.as_bytes());
    digest.iter().fold(String::from("sha256:"), |mut id, byte| {
        // Writing to a `String` cannot fail.
        let _ = write!(id, "{byte:02x}");
        id
    })
}
